#
#Thu Apr 30 13:27:07 ECT 2026
goog\:chromeOptions={args\=[start-maximized, test-type, ignore-certificate-errors, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins\=*, remote-allow-origins\=*, --start-maximized, --disable-notifications, --remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
